plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.0'
	id 'io.spring.dependency-management' version '1.1.5'
}

group = 'com.server'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// ModelMapper for object mapping
	implementation 'org.modelmapper:modelmapper:2.3.8'

	// MongoDB support
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.mongodb:mongodb-driver-sync:5.1.2'

	// Spring Web for building web applications, including RESTful services
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Lombok to reduce boilerplate code
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Thymeleaf for rendering web pages (e.g., login page)
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// AWS SDK for Polly and S3 services
	implementation 'software.amazon.awssdk:polly:2.20.0'
	implementation 'software.amazon.awssdk:auth:2.20.0'
	implementation 'software.amazon.awssdk:s3:2.20.0'

	// Spring WebFlux for reactive web applications
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// MySQL connector (if you plan to use MySQL, otherwise remove)
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Netty DNS resolver for macOS
	implementation 'io.netty:netty-resolver-dns-native-macos:4.1.71.Final'

	// Spring Boot Test Starter for testing Spring Boot applications
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'org.apache.commons:commons-lang3:3.12.0'

	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

tasks.named('test') {
	useJUnitPlatform()
}
